#pragma once

#include <glm/glm.hpp>

#include "ShaderProgram.h"
#include "TextureManager.h"

#include <string>
#include <unordered_map>

/**
 * @class Material
 * 
 * @brief Base class representing a renderable material in the engine.
 *
 * A Material encapsulates the visual appearance applied to a Model during
 * rendering. It is responsible for defining which shader program is used
 * and which textures are bound to that shader. Specific material types
 * (e.g., PhongMaterial, ...) should derive from this class and
 * override the apply_uniforms() method to set shader-specific uniform values.
 *
 * The Material does not perform actual rendering; instead, it prepares
 * the shader state (textures + uniforms) so that a Model can be correctly
 * drawn by the Renderer.
 */
class Material
{
public:

    /**
     * @brief Constructs a new Material with a name and an associated shader.
     * 
     * @param name Name used to identify the material.
     * @param shader Pointer to the ShaderProgram used to render this material.
     */
    Material(const std::string& name, ShaderProgram* shader);

    /**
     * @brief Virtual destructor
     */
    virtual ~Material() = default;

    /**
     * @brief Loads from disk the textures for the material
     *
     * The textures information are provided through TextureInfo structures, 
     * generated by the Model loading system. This method actually loads them
     * when the material is set to a model (so we will need them).
     *
     * @param textures List of texture metadata we need for this material
     */
    void load_textures(const std::vector<TextureInfo>& textures);

    /**
     * @brief Binds all textures associated with this material.
     *
     * This method assigns available texture units sequentially and binds
     * each stored texture to its corresponding uniform in the shader.
     * Should be called before any draw call that uses this material.
     */
    void bind_textures() const;

    /**
     * @brief Applies uniform values specific to this material.
     *
     * The base class version does nothing. Derived materials should override
     * this function to set shader uniforms such as colors, roughness,
     * shininess, metallic, emission, etc.
     */
    virtual void apply_uniforms() const = 0;

    /**
     * @brief Returns the material's identifier name.
     * 
     * @return String reference used to identify the material.
     */
    const std::string& get_name() const { return m_name; }

    /**
     * @brief Returns the shader associated with this material.
     * 
     * @return Pointer to the ShaderProgram used by this material.
     */
    ShaderProgram* get_shader() const { return m_shader; }

protected:

    // Shader program used for rendering
    ShaderProgram* m_shader;

private:

    // Identifier name of the material
    std::string     m_name;

    // Mapping of shader uniform names to bound textures
    std::unordered_map<std::string, Texture*> m_textures;
};